sudo: true
language: go
go:
  - 1.5.1
go_import_path: github.com/emccode/gorackhd
install:
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo wget -nv https://releases.hashicorp.com/vagrant/1.7.4/vagrant_1.7.4_x86_64.deb
  - sudo dpkg -i vagrant_1.7.4_x86_64.deb
  - git clone https://github.com/RackHD/RackHD.git .rackhd
  - cp .rackhd/example/config/monorail_rack.cfg.example .rackhd/example/config/monorail_rack.cfg
  - cd .rackhd/example && bin/monorail_rack
script:
  - make client-bindings
  - make install
